export enum modelArray {
  CATEGORY = 'categoryModel',
  STORE = 'storeModel',
  BANNER = 'bannerModel',
  SUB_CAT = 'sub_categoryModel',
  PRODUCT = 'productModel',
  SUPPORT = 'supportModel',
  USER = 'userModel',
  BANKDETAILS = 'bankDetailsModel',
  PRODUCTDETAILS = 'productDetailsModel',
  ORDER = 'orderModel',
  STOREOPENCLOSE = 'storeOpenCloseModel',
  ORDERHISTORY = 'orderHistoryModel',
  FEEDBACK ='feedbackModel',
  Commission = 'commissionModel',
  CITY ='cityModel',
  STATE ='stateModel',
  COUNTRY ='countryModel',
}
